### ISSUE TITLE
Add recipes for three potions

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/Alchemy#1]
Currently, the ItemUseSpeedPotion, ResistPhysicalPotion, and ResistPoisonPotion don't have recipes in this module. So, they can't be created unless using the debug utils.

Thus, the job here is to provide the recipe prefabs. Use the other potion recipe prefabs as templates.

**Comment by RobRoseKnows** [comment]
I can take care of this.

**Comment by Cervator** [comment]
@RobRoseKnows Awesome! Go forth and do great things :-)

**Comment by RobRoseKnows** [comment]
Are there recipes already decided or should I just make my own?

**Comment by RobRoseKnows** [comment]
Another question: Should I only make recipes and the necessary herb prefabs to make them or should I be modifying the .java files as well. For example, should I add the new Herbs to the HerbForestSpawnDefinition.java?

**Comment by skaldarnar** [comment]
You can search in the forums if there are already recipes, otherwise just
made them up. They are pretty simple to change later on.

You can do this issue stepwise. First, define the recipe prefabs and commit
them (to your fork). Second, try to integrate the herbs etc. into world gen.

If you run into problems we are glad to help you out :wink:

**Comment by xrtariq2594** [comment]
@RobRoseKnows Make your own recipes and herbs were you see fit. As long as the final result is one of the aforementioned potions, it's fine. We can always fine tune the details later.

**Comment by syntaxi** [comment]
Closing as fixed by PR #6
